export enum ImportJobStatus { PENDING="PENDING", VALIDATING="VALIDATING", VALIDATED="VALIDATED", PARTIAL="PARTIAL", READY_TO_APPLY="READY_TO_APPLY", APPLYING="APPLYING", APPLIED="APPLIED", FAILED="FAILED", CANCELLED="CANCELLED" }
export enum ExportJobStatus { PENDING="PENDING", EXPORTING="EXPORTING", COMPLETED="COMPLETED", FAILED="FAILED", CANCELLED="CANCELLED" }
export enum ImportKind { WAREHOUSE="WAREHOUSE", LOCATION="LOCATION", TASK="TASK" }
export enum ExportKind { WAREHOUSE="WAREHOUSE", LOCATION="LOCATION", TASK="TASK", DOCUMENT="DOCUMENT" }
export const VALID_IMPORT_KINDS = Object.values(ImportKind);
export const VALID_EXPORT_KINDS = Object.values(ExportKind);
