export enum InventoryEventStatus {
  PENDING = "PENDING",
  READY = "READY",
  PUBLISHED = "PUBLISHED",
  CONSUMED = "CONSUMED",
  FAILED = "FAILED",
  DEAD_LETTER = "DEAD_LETTER",
  REPLAY_REQUESTED = "REPLAY_REQUESTED",
  REPLAYED = "REPLAYED",
  CANCELLED = "CANCELLED",
}
