import { InventoryImportJob, InventoryExportJob, type ImportJobListFilters, type ExportJobListFilters, type ImportJobListResult, type ExportJobListResult, type InventoryImportExportRepository, type ImportJobSnapshot } from "@sunset/domain";
import { Prisma, type PrismaClient } from "@prisma/client";
import { prisma as defaultPrisma } from "../client";
type DbClient = PrismaClient | Prisma.TransactionClient;
export class PrismaImportExportRepository implements InventoryImportExportRepository {
  constructor(private readonly db: DbClient = defaultPrisma) {}
  async saveImportJob(job: InventoryImportJob, db?: DbClient): Promise<void> {
    const c = db ?? this.db; const s = job.toSnapshot();
    await (c as any).inventoryImportJob.upsert({ where: { id: s.id }, create: { id: s.id, organizationId: s.organizationId, kind: s.kind, status: s.status, fileName: s.fileName, fileMimeType: s.fileMimeType, fileSize: s.fileSize, fileHash: s.fileHash, fileStorageKey: s.fileStorageKey, totalRows: s.totalRows, validRows: s.validRows, invalidRows: s.invalidRows, appliedRows: s.appliedRows, requestedByUserId: s.requestedByUserId, confirmedByUserId: s.confirmedByUserId, startedAt: s.startedAt ? new Date(s.startedAt) : null, validatedAt: s.validatedAt ? new Date(s.validatedAt) : null, appliedAt: s.appliedAt ? new Date(s.appliedAt) : null, failedAt: s.failedAt ? new Date(s.failedAt) : null, cancelledAt: s.cancelledAt ? new Date(s.cancelledAt) : null, correlationId: s.correlationId, idempotencyKey: s.idempotencyKey, version: s.version, createdAt: new Date(s.createdAt), updatedAt: new Date(s.updatedAt) }, update: { status: s.status, fileStorageKey: s.fileStorageKey, totalRows: s.totalRows, validRows: s.validRows, invalidRows: s.invalidRows, appliedRows: s.appliedRows, confirmedByUserId: s.confirmedByUserId, startedAt: s.startedAt ? new Date(s.startedAt) : null, validatedAt: s.validatedAt ? new Date(s.validatedAt) : null, appliedAt: s.appliedAt ? new Date(s.appliedAt) : null, failedAt: s.failedAt ? new Date(s.failedAt) : null, cancelledAt: s.cancelledAt ? new Date(s.cancelledAt) : null, version: s.version, updatedAt: new Date(s.updatedAt) } });
  }
  async findImportJobById(id: string): Promise<InventoryImportJob | null> { const r = await (this.db as any).inventoryImportJob.findUnique({ where: { id }, include: { errors: { orderBy: { rowNumber: "asc" } } } }); return r ? InventoryImportJob.rehydrate(this.toImportSnapshot(r)) : null; }
  async findImportJobByIdempotencyKey(k: string): Promise<ImportJobSnapshot | null> { const r = await (this.db as any).inventoryImportJob.findUnique({ where: { idempotencyKey: k }, include: { errors: { orderBy: { rowNumber: "asc" } } } }); return r ? this.toImportSnapshot(r) : null; }
  async listImportJobs(f: ImportJobListFilters = {}, page = 1, limit = 20): Promise<ImportJobListResult> { const w: any = {}; if (f.organizationId) w.organizationId = f.organizationId; if (f.kind) w.kind = f.kind; if (f.status) w.status = f.status; if (f.requestedByUserId) w.requestedByUserId = f.requestedByUserId; const t = Math.min(Math.max(limit, 1), 100); const s = (Math.max(page, 1) - 1) * t; const total = await (this.db as any).inventoryImportJob.count({ where: w }); const rows = await (this.db as any).inventoryImportJob.findMany({ where: w, take: t, skip: s, include: { errors: { orderBy: { rowNumber: "asc" } } }, orderBy: { createdAt: "desc" } }); return { data: rows.map((r: any) => InventoryImportJob.rehydrate(this.toImportSnapshot(r))), total }; }
  async saveImportErrors(jobId: string, errors: { rowNumber: number; field?: string; code: string; message: string; severity?: string }[], db?: DbClient): Promise<void> { const c = db ?? this.db; await (c as any).inventoryImportJobError.deleteMany({ where: { jobId } }); if (errors.length) await (c as any).inventoryImportJobError.createMany({ data: errors.map(e => ({ jobId, rowNumber: e.rowNumber, field: e.field || null, code: e.code, message: e.message, severity: e.severity || "ERROR" })) }); }
  async getImportErrors(jobId: string) { const rows = await (this.db as any).inventoryImportJobError.findMany({ where: { jobId }, orderBy: { rowNumber: "asc" } }); return rows.map((r: any) => ({ rowNumber: r.rowNumber, field: r.field, code: r.code, message: r.message, severity: r.severity })); }
  async saveExportJob(job: InventoryExportJob, db?: DbClient): Promise<void> { const c = db ?? this.db; const s = job.toSnapshot(); await (c as any).inventoryExportJob.upsert({ where: { id: s.id }, create: { id: s.id, organizationId: s.organizationId, kind: s.kind, status: s.status, format: s.format, filters: s.filters, fileName: s.fileName, fileHash: s.fileHash, fileStorageKey: s.fileStorageKey, rowCount: s.rowCount, requestedByUserId: s.requestedByUserId, completedAt: s.completedAt ? new Date(s.completedAt) : null, failedAt: s.failedAt ? new Date(s.failedAt) : null, cancelledAt: s.cancelledAt ? new Date(s.cancelledAt) : null, correlationId: s.correlationId, version: s.version, createdAt: new Date(s.createdAt), updatedAt: new Date(s.updatedAt) }, update: { status: s.status, fileHash: s.fileHash, fileStorageKey: s.fileStorageKey, rowCount: s.rowCount, completedAt: s.completedAt ? new Date(s.completedAt) : null, failedAt: s.failedAt ? new Date(s.failedAt) : null, cancelledAt: s.cancelledAt ? new Date(s.cancelledAt) : null, version: s.version, updatedAt: new Date(s.updatedAt) } }); }
  async findExportJobById(id: string): Promise<InventoryExportJob | null> { const r = await (this.db as any).inventoryExportJob.findUnique({ where: { id } }); return r ? InventoryExportJob.rehydrate(this.toExportSnapshot(r)) : null; }
  async listExportJobs(f: ExportJobListFilters = {}, page = 1, limit = 20): Promise<ExportJobListResult> { const w: any = {}; if (f.organizationId) w.organizationId = f.organizationId; if (f.kind) w.kind = f.kind; if (f.status) w.status = f.status; if (f.requestedByUserId) w.requestedByUserId = f.requestedByUserId; const t = Math.min(Math.max(limit, 1), 100); const s = (Math.max(page, 1) - 1) * t; const total = await (this.db as any).inventoryExportJob.count({ where: w }); const rows = await (this.db as any).inventoryExportJob.findMany({ where: w, take: t, skip: s, orderBy: { createdAt: "desc" } }); return { data: rows.map((r: any) => InventoryExportJob.rehydrate(this.toExportSnapshot(r))), total }; }
  private toImportSnapshot(r: any): any { return { id: r.id, organizationId: r.organizationId, kind: r.kind, status: r.status, fileName: r.fileName, fileMimeType: r.fileMimeType, fileSize: r.fileSize, fileHash: r.fileHash, fileStorageKey: r.fileStorageKey, totalRows: r.totalRows, validRows: r.validRows, invalidRows: r.invalidRows, appliedRows: r.appliedRows, requestedByUserId: r.requestedByUserId, confirmedByUserId: r.confirmedByUserId, startedAt: r.startedAt?.toISOString() ?? null, validatedAt: r.validatedAt?.toISOString() ?? null, appliedAt: r.appliedAt?.toISOString() ?? null, failedAt: r.failedAt?.toISOString() ?? null, cancelledAt: r.cancelledAt?.toISOString() ?? null, correlationId: r.correlationId, idempotencyKey: r.idempotencyKey, errors: (r.errors ?? []).map((e: any) => ({ rowNumber: e.rowNumber, field: e.field, code: e.code, message: e.message, severity: e.severity })), version: r.version, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString() }; }
  private toExportSnapshot(r: any): any { return { id: r.id, organizationId: r.organizationId, kind: r.kind, status: r.status, format: r.format, filters: r.filters, fileName: r.fileName, fileHash: r.fileHash, fileStorageKey: r.fileStorageKey, rowCount: r.rowCount, requestedByUserId: r.requestedByUserId, completedAt: r.completedAt?.toISOString() ?? null, failedAt: r.failedAt?.toISOString() ?? null, cancelledAt: r.cancelledAt?.toISOString() ?? null, correlationId: r.correlationId, version: r.version, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString() }; }
}
